services:
  backend:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "4173:4173"
    env_file:
      - ../frontend/.env
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: